### PR TITLE
Gabriel's `basic-coverage` with codecov CI 

### PR DESCRIPTION
**Pull request by KevinEady**

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
I can't get the codecov report to show me the lines covered/not covered. Could the 64% be because it somehow merges the percentages for lines, branches, functions, etc?

**Comment by KevinEady** [comment]
@gabrielschulhof can you see the coverage lines here? https://app.codecov.io/gh/KevinEady/node-addon-api/commit/74f1636fd6162c40cab2a80510d9da1d73cf6b89/tree 

And I don't know about the percentage being low due to merging... 🤷 not sure how to verify that

**Comment by gabrielschulhof** [comment]
@KevinEady Oh, cool! Yeah, I can see the files now.

**Comment by gabrielschulhof** [comment]
This is weird:
image
If the if-statement got evaluated, either the body or the line following it should've been covered.

**Comment by KevinEady** [comment]
With optimizations disabled: https://app.codecov.io/github/KevinEady/node-addon-api/commit/9d052a34ac57f62ee888f8925d2645892c5c2bff/tree seems to be lower

**Comment by KevinEady** [comment]
@gabrielschulhof I did a little more digging and debugging on commit https://github.com/KevinEady/node-addon-api/pull/6/commits/f8e65ba7d8d9a29e0bbaa1639980391a6496f0af which now uploads the [HTML report as an artifact](https://github.com/KevinEady/node-addon-api/actions/runs/8024611058/artifacts/1270886267) which shows >93% coverage like yours.

Reading https://docs.codecov.com/docs/about-code-coverage:

> Coverage is the ratio of `hits / (sum of hit + partial + miss)`

And https://docs.codecov.com/docs/about-code-coverage:

> - **hit** indicates that the source code was executed by the test suite.
> - **partial** indicates that the source code was not fully executed by the test suite; there are remaining branches that were not executed.
> - **miss** indicates that the source code was not executed by the test suite.

codecov has the following stats on `napi-inl.h` for this commit ([report](https://app.codecov.io/github/KevinEady/node-addon-api/commit/f8e65ba7d8d9a29e0bbaa1639980391a6496f0af/tree)):
|tracked|hits|partial|missed|coverage|
|-|-|-|-|-|
|1960|1275|553 |132|65%|

Then 65% makes sense, as `1275 / ( 1275 + 553 + 132 ) = 65%`

However, the gcovr HTML report gives a 93.7% line coverage, which I believe is because gcovr considers  _partials_ as _hits_, as if you do `(hits + partials) / (hits + partials + missed) = (1275 + 553) / ( 1275 + 553 + 132 ) = 93%`

So, I believe this is why there's a discrepancy between the gcovr HTML and codecov Web report.

The HTML report shows partials as this little collapsable arrow, eg. looking at `Boolean::operator bool()`:

image

... but the line is still considered covered. 

I assume gcovr says this has branches because `Boolean::Value()` is inlined, which has a `NAPI_THROW_IF_FAILED` macro.

So, not particularly sure how we want to proceed now.
 
cc: @mhdawson @legendecas @vmoroz

**Pull request merged**
